version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: gateway
    ports:
    - "8002:8002"
    volumes:
    - .:/app/src/
    restart: always
    env_file:
    - .env
    environment:
      HOST: 0.0.0.0
      PORT: 8002
      RELOAD: "True"
      GESTAO_HOST: http://gestao:8001
      PATRIMONIO_HOST: http://patrimonio:8000
    networks:
    - sindpol_network

networks:
  sindpol_network:
    external: true
    driver: 'bridge'
