name: Generate Metrics Release

on:
  release:
    types: [released]
  pull_request:
    types:
      - closed

jobs:
  send-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Metrics SonarCloud
        run: python3 metrics/sonar-metrics.py ${{ github.event.repository.name }} ${{ github.ref_name }}

      - name: Commit Metrics SonarCloud File
        run: |
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.name "${{ secrets.USER_USERNAME }}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_GITHUB}}@github.com/fga-eps-mds/${{secrets.GIT_DOC_REPO}}" ${{secrets.GIT_DOC_REPO}}
          mkdir -p ${{secrets.GIT_DOC_REPO}}/analytics-raw-data
          cp -R analytics-raw-data/*.json ${{secrets.GIT_DOC_REPO}}/analytics-raw-data
          cd ${{secrets.GIT_DOC_REPO}}
          git add .
          git commit -m "Gerando métricas SonarCloud - ${{ github.event.repository.name }} ${{ github.ref_name }}"
          git push
          echo "Metrics File Generated Successfully."
